// constants/types.ts

// ==========================================
// 1. CORE LOCATION & MAPS
// ==========================================

/**
 * Universal coordinate structure used throughout the app.
 * Decouples the app from specific Google Maps types for easier refactoring.
 */
export type GeoPoint = {
    lat: number;
    lng: number;
};

/**
 * Represents a raw location object fetched from the Google Places API.
 * Used for Hotels, Restaurants, and Activities.
 */
export type GooglePlace = {
    /** The display name of the place */
    name: string;
    /** Google's unique identifier for this place. Crucial for key attributes in lists. */
    place_id: string;
    /** Rating from 1.0 to 5.0 */
    rating?: number;
    /** Total number of reviews */
    user_ratings_total?: number;
    /** A simplified address or description of the area */
    vicinity?: string;
    /** The full human-readable address */
    formatted_address?: string;
    /** Cost level: 0 (Free) to 4 (Very Expensive) */
    price_level?: number;

    geometry: {
        location: GeoPoint;
    };
    /** Array of photo references used to fetch images via the Places Photo API */
    photos?: { photo_reference: string }[];
};

/**
 * Stores navigation data between two distinct points.
 */
export type RouteDetails = {
    /** Distance stored in METERS. Frontend should handle conversion to Miles or Km. */
    distanceMeters: number;
    /** Human readable duration (e.g., "4 hours 10 mins") returned by API */
    durationText: string;
    startLocation: GeoPoint;
    endLocation: GeoPoint;

    /** Encoded polyline string for drawing the route on a map */
    overview_polyline?: {
        points: string;
    };
};

// ==========================================
// 2. AI SERVICE & INPUTS
// ==========================================

/**
 * Defines the "personality" of the trip generation.
 */
export type TripVibe = 'balanced' | 'comfort' | 'explorer' | 'foodie';

/**
 * The payload sent to the AI Service (Gemini) to generate a trip.
 */
export type AiTripInput = {
    origin: string;
    destination: string;
    duration: number;
    budget: number;
    travelers: {
        adults: number;
        children: number;
    };
    carName: string;
    mpg: string | number;
    gasPrice: string | number;
    vibe: TripVibe;
    isRoundTrip: boolean;
};

// ==========================================
// 3. BUDGET & FINANCIALS
// ==========================================

export type CategoryType = 'fuel' | 'hotel' | 'food' | 'activities' | 'other';

export type BudgetCategory = {
    category: CategoryType;
    amount: number;
};

// ==========================================
// 4. TRIP DATA MODEL
// ==========================================

/**
 * Represents a specific day (or segment) within the trip plan.
 */
export type ItineraryItem = {
    id: string;
    order: number;
    day: number;
    routePolyline?: string;
    routeStats?: {
        distance: string;
        duration: string;
    };
    title: string;
    description: string;
    fuel_cost: number;
    drive_time: string;
    start_city: string;
    end_city: string;

    // AI Suggestions
    hotel_options: GooglePlace[];
    food_options: GooglePlace[];
    activity_options: GooglePlace[];

    // User Selections (optional until selected)
    selected_hotel_id?: string;
    selected_food_id?: string;
    selected_activity_id?: string;

    coordinates: GeoPoint;

    // NEW: Flexible timeline for drag-and-drop activities
    timeline?: any[];
    stopLocation?: GeoPoint;
    distance?: string;
};

/**
 * Defines a user with access to the trip.
 */
export type TripMember = {
    uid: string;
    name: string;
    avatar?: string;
    role: 'owner' | 'editor' | 'viewer';
};

/**
 * The core document definition stored in the database (Firestore).
 */
export type Trip = {
    /** Database Document ID (generated by Firestore) */
    id?: string;
    userId: string;

    startCity: string;
    endCity: string;
    destination: string;

    overviewPolyline?: string;
    overviewStats?: Record<string, { distance: string; duration: string }>;
    // --- NESTED OBJECTS (Refactored for Consistency) ---
    travelers: {
        adults: number;
        children: number;
    };
    vehicle: {
        name: string;
        mpg: number;
        gasPrice: number;
    };
    // --------------------------------------------------

    mode: 'ai' | 'manual'; // <--- ADDED: Trip mode
    vibe: string | null;
    notes?: string;
    aiNote?: string;
    budget: number;
    estimatedCost: number;
    estimatedBreakdown: BudgetCategory[];

    duration: number;
    people: number; // Keep for backward compatibility or simple counts

    startDate: string | null;
    endDate: string | null;

    image: string;

    itinerary: ItineraryItem[];
    members: TripMember[];

    /** Server Timestamp */
    createdAt: any;

    /** For Manual Trips: Optional coordinates to center the map */
    originCoordinates?: GeoPoint;

    /** Track actual spending vs budget */
    spent?: number;
};

/**
 * Helper type for creating a new trip before the ID is assigned.
 */
export type TripPayload = Omit<Trip, 'id' | 'userId' | 'createdAt'>;